name: Scheduled Job

on:
  schedule:
    - cron: "11 7 * * *"   # Optional: allow manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run the script
        run: python3 reminder.py
